import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
    products: [
    {
      name: 'Pineapple Cake',
      slug: 'pineapple-cake',
      category: 'Cakes',
      image: '/images/p1.jpeg',
      price: 150,
      countInStock: 10,
      brand: 'FreshBake',
      rating: 4.5,
      numReviews: 10,
      description: 'Delicious pineapple-flavored cake',
    },
    {
      name: 'Chocolate Truffle Cake',
      slug: 'chocolate-truffle-cake',
      category: 'Cakes',
      image: '/images/p2.jpeg',
      price: 250,
      countInStock: 15,
      brand: 'SweetTreats',
      rating: 4.8,
      numReviews: 20,
      description: 'Rich chocolate truffle layered cake',
    },
    {
      name: 'Blueberry Muffins',
      slug: 'blueberry-muffins',
      category: 'Muffins',
      image: '/images/p3.jpeg',
      price: 200,
      countInStock: 25,
      brand: 'BakeryFresh',
      rating: 4.2,
      numReviews: 8,
      description: 'Soft muffins filled with blueberry chunks',
    },
    {
      name: 'Vanilla Cupcakes',
      slug: 'vanilla-cupcakes',
      category: 'Cupcakes',
      image: '/images/p4.jpeg',
      price: 100,
      countInStock: 20,
      brand: 'CupcakeWorld',
      rating: 4.0,
      numReviews: 5,
      description: 'Classic vanilla cupcakes with creamy frosting',
    },
    {
      name: 'Strawberry Pastry',
      slug: 'strawberry-pastry',
      category: 'Pastries',
      image: '/images/p5.jpeg',
      price: 150,
      countInStock: 30,
      brand: 'PastryHouse',
      rating: 4.3,
      numReviews: 12,
      description: 'Fluffy pastry with fresh strawberry cream',
    },
    {
      name: 'Oreo Cheesecake',
      slug: 'oreo-cheesecake',
      category: 'Cheesecakes',
      image: '/images/p6.jpeg',
      price: 300,
      countInStock: 8,
      brand: 'CheesyDelight',
      rating: 4.7,
      numReviews: 18,
      description: 'Creamy cheesecake loaded with Oreo cookies',
    },
    {
      name: 'Keto Almond Cookies',
      slug: 'keto-almond-cookies',
      category: 'Cookies',
      image: '/images/p7.jpeg', // Using p7 until p8 is added
      price: 250,
      countInStock: 12,
      brand: 'HealthyBites',
      rating: 4.4,
      numReviews: 9,
      description: 'Low-carb keto cookies made with almond flour',
    }
  ],
};
export default data;
